// playground/the-vue-point/src/components/NavBarLinks.svelte
<div class="text-sm text-gray-500 leading-5">
  <a
    class="hover:text-gray-700"
    href="https://github.com/ElMassimo/iles/tree/main/playground/the-vue-point"
    target="_blank"
    rel="noopener noreferrer"
    ><span class="hidden sm:inline">GitHub</span> Source</a
  >
  <span class="mr-1 ml-1">·</span>
  <a class="hover:text-gray-700" href="/feed.rss">RSS <span class="hidden sm:inline">Feed</span></a>
  <span class="mr-1 ml-1">·</span>
  <a
    class="hover:text-gray-700"
    href="https://vuejs.org"
    target="_blank"
    rel="noopener noreferrer"
    >Vuejs.org →</a
  >
</div>

// playground/the-vue-point/src/components/NavBarLinks.vue
<template>
  <div class="text-sm text-gray-500 leading-5">
    <a
      class="hover:text-gray-700"
      href="/cat-zone"
    >Cat Zone</a>
    <span class="mr-1 ml-1">·</span>
    <a
      class="hover:text-gray-700"
      href="https://github.com/ElMassimo/iles/tree/main/playground/the-vue-point"
      target="_blank"
      rel="noopener noreferrer"
    ><span class="hidden sm:inline">GitHub</span> Source</a>
    <span class="mr-1 ml-1">·</span>
    <a class="hover:text-gray-700" href="/feed.rss">RSS <span class="hidden sm:inline">Feed</span></a>
    <span class="mr-1 ml-1">·</span>
    <a
      class="hover:text-gray-700"
      href="https://vuejs.org"
      target="_blank"
      rel="noopener noreferrer"
    >Vuejs.org →</a>
  </div>
</template>
